package com.scaling.libraryservice.commons.api.util.binding;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.function.Executable;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

class LoanItemBindingTest {

    private ResponseEntity<String> response;

    @BeforeEach
    public void setUp(){
        String body = "{\n"
            + "    \"response\": {\n"
            + "        \"request\": {\n"
            + "            \"pageNo\": 1,\n"
            + "            \"pageSize\": 10\n"
            + "        },\n"
            + "        \"resultNum\": 10,\n"
            + "        \"numFound\": 5000,\n"
            + "        \"docs\": [\n"
            + "            {\n"
            + "                \"doc\": {\n"
            + "                    \"no\": 1,\n"
            + "                    \"ranking\": \"1\",\n"
            + "                    \"bookname\": \"나미야 잡화점의 기적 :히가시노 게이고 장편소설 \",\n"
            + "                    \"authors\": \"지은이: 히가시노 게이고 ;옮긴이: 양윤옥\",\n"
            + "                    \"publisher\": \"현대문학\",\n"
            + "                    \"publication_year\": \"2012\",\n"
            + "                    \"isbn13\": \"9788972756194\",\n"
            + "                    \"addition_symbol\": \"03830\",\n"
            + "                    \"vol\": \"\",\n"
            + "                    \"class_no\": \"833.6\",\n"
            + "                    \"class_nm\": \"문학 > 일본문학 > 소설\",\n"
            + "                    \"loan_count\": \"340252\",\n"
            + "                    \"bookImageURL\": \"http://image.aladin.co.kr/product/15848/6/cover/k622533431_1.jpg\",\n"
            + "                    \"bookDtlUrl\": \"https://data4library.kr/bookV?seq=1902173\"\n"
            + "                }\n"
            + "            },\n"
            + "            {\n"
            + "                \"doc\": {\n"
            + "                    \"no\": 2,\n"
            + "                    \"ranking\": \"2\",\n"
            + "                    \"bookname\": \"엄마를 부탁해 :신경숙 장편소설 \",\n"
            + "                    \"authors\": \"지은이: 신경숙\",\n"
            + "                    \"publisher\": \"창비\",\n"
            + "                    \"publication_year\": \"2008\",\n"
            + "                    \"isbn13\": \"9788936433673\",\n"
            + "                    \"addition_symbol\": \"03810\",\n"
            + "                    \"vol\": \"\",\n"
            + "                    \"class_no\": \"813.6\",\n"
            + "                    \"class_nm\": \"문학 > 한국문학 > 소설\",\n"
            + "                    \"loan_count\": \"278612\",\n"
            + "                    \"bookImageURL\": \"http://image.aladin.co.kr/product/272/78/cover/8936433679_2.jpg\",\n"
            + "                    \"bookDtlUrl\": \"https://data4library.kr/bookV?seq=2271872\"\n"
            + "                }\n"
            + "            },\n"
            + "            {\n"
            + "                \"doc\": {\n"
            + "                    \"no\": 3,\n"
            + "                    \"ranking\": \"3\",\n"
            + "                    \"bookname\": \"7년의 밤 :정유정 장편소설 \",\n"
            + "                    \"authors\": \"지은이: 정유정\",\n"
            + "                    \"publisher\": \"은행나무\",\n"
            + "                    \"publication_year\": \"2011\",\n"
            + "                    \"isbn13\": \"9788956604992\",\n"
            + "                    \"addition_symbol\": \"03810\",\n"
            + "                    \"vol\": \"\",\n"
            + "                    \"class_no\": \"813.7\",\n"
            + "                    \"class_nm\": \"문학 > 한국문학 > 소설\",\n"
            + "                    \"loan_count\": \"239181\",\n"
            + "                    \"bookImageURL\": \"http://image.aladin.co.kr/product/14712/55/cover/k202532053_1.jpg\",\n"
            + "                    \"bookDtlUrl\": \"https://data4library.kr/bookV?seq=1153285\"\n"
            + "                }\n"
            + "            },\n"
            + "            {\n"
            + "                \"doc\": {\n"
            + "                    \"no\": 4,\n"
            + "                    \"ranking\": \"4\",\n"
            + "                    \"bookname\": \"(趙廷來 大河小說) 太白山脈 \",\n"
            + "                    \"authors\": \"저자: 조정래\",\n"
            + "                    \"publisher\": \"해냄\",\n"
            + "                    \"publication_year\": \"2002\",\n"
            + "                    \"isbn13\": \"9788973374113\",\n"
            + "                    \"addition_symbol\": \"03810\",\n"
            + "                    \"vol\": \"4\",\n"
            + "                    \"class_no\": \"813.62\",\n"
            + "                    \"class_nm\": \"문학 > 한국문학 > 소설\",\n"
            + "                    \"loan_count\": \"226311\",\n"
            + "                    \"bookImageURL\": \"http://image.aladin.co.kr/product/29/99/cover/8973374117_1.jpg\",\n"
            + "                    \"bookDtlUrl\": \"https://data4library.kr/bookV?seq=2435248\"\n"
            + "                }\n"
            + "            },\n"
            + "            {\n"
            + "                \"doc\": {\n"
            + "                    \"no\": 5,\n"
            + "                    \"ranking\": \"5\",\n"
            + "                    \"bookname\": \"뚱딴지 명언 산책\",\n"
            + "                    \"authors\": \"김우영 글.그림\",\n"
            + "                    \"publisher\": \"재능출판\",\n"
            + "                    \"publication_year\": \"1997\",\n"
            + "                    \"isbn13\": \"9788976491114\",\n"
            + "                    \"addition_symbol\": \"77810\",\n"
            + "                    \"vol\": \"\",\n"
            + "                    \"class_no\": \"199.1\",\n"
            + "                    \"class_nm\": \"철학 > 윤리학, 도덕철학 > 도덕훈, 교훈\",\n"
            + "                    \"loan_count\": \"219694\",\n"
            + "                    \"bookImageURL\": \"https://bookthumb-phinf.pstatic.net/cover/013/434/01343405.jpg?type=m1&udate=20071117\",\n"
            + "                    \"bookDtlUrl\": \"https://data4library.kr/bookV?seq=331163\"\n"
            + "                }\n"
            + "            },\n"
            + "            {\n"
            + "                \"doc\": {\n"
            + "                    \"no\": 6,\n"
            + "                    \"ranking\": \"6\",\n"
            + "                    \"bookname\": \"채식주의자:한강 연작소설\",\n"
            + "                    \"authors\": \"한강\",\n"
            + "                    \"publisher\": \"창비\",\n"
            + "                    \"publication_year\": \"2007\",\n"
            + "                    \"isbn13\": \"9788936433598\",\n"
            + "                    \"addition_symbol\": \"03810\",\n"
            + "                    \"vol\": \"\",\n"
            + "                    \"class_no\": \"813.6\",\n"
            + "                    \"class_nm\": \"문학 > 한국문학 > 소설\",\n"
            + "                    \"loan_count\": \"200122\",\n"
            + "                    \"bookImageURL\": \"https://bookthumb-phinf.pstatic.net/cover/033/094/03309417.jpg?type=m1&udate=20180609\",\n"
            + "                    \"bookDtlUrl\": \"https://data4library.kr/bookV?seq=2155671\"\n"
            + "                }\n"
            + "            },\n"
            + "            {\n"
            + "                \"doc\": {\n"
            + "                    \"no\": 7,\n"
            + "                    \"ranking\": \"7\",\n"
            + "                    \"bookname\": \"미움받을 용기 :자유롭고 행복한 삶을 위한 아들러의 가르침 \",\n"
            + "                    \"authors\": \"기시미 이치로,전경아 옮김\",\n"
            + "                    \"publisher\": \"인플루엔셜\",\n"
            + "                    \"publication_year\": \"2014\",\n"
            + "                    \"isbn13\": \"9788996991342\",\n"
            + "                    \"addition_symbol\": \"13180\",\n"
            + "                    \"vol\": \"\",\n"
            + "                    \"class_no\": \"189.2\",\n"
            + "                    \"class_nm\": \"철학 > 심리학 > 응용심리학 일반\",\n"
            + "                    \"loan_count\": \"193395\",\n"
            + "                    \"bookImageURL\": \"https://bookthumb-phinf.pstatic.net/cover/083/399/08339910.jpg?type=m1&udate=20180616\",\n"
            + "                    \"bookDtlUrl\": \"https://data4library.kr/bookV?seq=2396926\"\n"
            + "                }\n"
            + "            },\n"
            + "            {\n"
            + "                \"doc\": {\n"
            + "                    \"no\": 8,\n"
            + "                    \"ranking\": \"8\",\n"
            + "                    \"bookname\": \"82년생 김지영 :조남주 장편소설 \",\n"
            + "                    \"authors\": \"지은이: 조남주\",\n"
            + "                    \"publisher\": \"민음사\",\n"
            + "                    \"publication_year\": \"2016\",\n"
            + "                    \"isbn13\": \"9788937473135\",\n"
            + "                    \"addition_symbol\": \"04810\",\n"
            + "                    \"vol\": \"\",\n"
            + "                    \"class_no\": \"813.7\",\n"
            + "                    \"class_nm\": \"문학 > 한국문학 > 소설\",\n"
            + "                    \"loan_count\": \"178724\",\n"
            + "                    \"bookImageURL\": \"https://bookthumb-phinf.pstatic.net/cover/112/111/11211133.jpg?type=m1&udate=20180530\",\n"
            + "                    \"bookDtlUrl\": \"https://data4library.kr/bookV?seq=3369923\"\n"
            + "                }\n"
            + "            },\n"
            + "            {\n"
            + "                \"doc\": {\n"
            + "                    \"no\": 9,\n"
            + "                    \"ranking\": \"9\",\n"
            + "                    \"bookname\": \"틀려도 괜찮아\",\n"
            + "                    \"authors\": \"마키타 신지 글;유문조 옮김\",\n"
            + "                    \"publisher\": \"토토북\",\n"
            + "                    \"publication_year\": \"2006\",\n"
            + "                    \"isbn13\": \"9788990611260\",\n"
            + "                    \"addition_symbol\": \"77830\",\n"
            + "                    \"vol\": \"\",\n"
            + "                    \"class_no\": \"833.6\",\n"
            + "                    \"class_nm\": \"문학 > 일본문학 > 소설\",\n"
            + "                    \"loan_count\": \"174034\",\n"
            + "                    \"bookImageURL\": \"http://image.aladin.co.kr/product/62/27/cover/8990611261_2.jpg\",\n"
            + "                    \"bookDtlUrl\": \"https://data4library.kr/bookV?seq=937338\"\n"
            + "                }\n"
            + "            },\n"
            + "            {\n"
            + "                \"doc\": {\n"
            + "                    \"no\": 10,\n"
            + "                    \"ranking\": \"10\",\n"
            + "                    \"bookname\": \"정글만리 :조정래 장편소설\",\n"
            + "                    \"authors\": \"저자: 조정래\",\n"
            + "                    \"publisher\": \"해냄출판사\",\n"
            + "                    \"publication_year\": \"2013\",\n"
            + "                    \"isbn13\": \"9788965744023\",\n"
            + "                    \"addition_symbol\": \"04810\",\n"
            + "                    \"vol\": \"1\",\n"
            + "                    \"class_no\": \"813.62\",\n"
            + "                    \"class_nm\": \"문학 > 한국문학 > 소설\",\n"
            + "                    \"loan_count\": \"170702\",\n"
            + "                    \"bookImageURL\": \"https://bookthumb-phinf.pstatic.net/cover/072/420/07242056.jpg?type=m1&udate=20180717\",\n"
            + "                    \"bookDtlUrl\": \"https://data4library.kr/bookV?seq=2373845\"\n"
            + "                }\n"
            + "            }\n"
            + "        ]\n"
            + "    }\n"
            + "}";

        response = new ResponseEntity<>(body, HttpStatus.OK);
    }

    @Test
    void bind() {
        /* given */
        LoanItemBinding loanItemBinding = new LoanItemBinding();

        /* when */

        Executable e = () -> loanItemBinding.bind(response);

        /* then */

        assertDoesNotThrow(e);

    }

}